language: objective-c 
osx_image: xcode8
xcode_workspace: CucumberishExample.xcworkspace
xcode_scheme: CucumberishExample
xcode_sdk: 'iPhone 7'
script: 
- xcodebuild clean build test -workspace CucumberishExample.xcworkspace -scheme CucumberishExample -destination 'platform=iOS Simulator,name=iphone 7' | xcpretty